- name: Deploy Linux Tweet App with NGINX and Docker
  hosts: web
  become: yes
  roles:
    - { role: docker, tags: ["docker"] }
    - { role: nginx, tags: ["nginx"] }
    - { role: app, tags: ["app"] }
