- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Ensure Docker is started and enabled
  service:
    name: docker
    state: started
    enabled: true

- name: Wait for Docker daemon to be ready
  wait_for:
    path: /var/run/docker.sock
    state: started
    timeout: 5