- name: Deploy linux_tweet_app
  hosts: web
  become: yes
  tasks:
    - name: Clone linux_tweet_app
      git:
        repo: https://github.com/dockersamples/linux_tweet_app.git
        dest: /opt/linux_tweet_app

    - name: Run the app with Docker
      shell: docker build -t linux_tweet_app /opt/linux_tweet_app && docker run -d --name tweet_app -p 5000:80 linux_tweet_app
      args:
        creates: /opt/linux_tweet_app
