- name: Configure NGINX
  hosts: web
  become: yes
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy NGINX config
      copy:
        src: ../nginx/default.conf
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: '0644'

    - name: Restart NGINX
      service:
        name: nginx
        state: restarted
